### ISSUE TITLE
Excluding loggers

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/logjam#13]
I'd like to exclude certain loggers, e.g. `org.eclipse.jetty.server.Server`, `org.eclipse.jetty.server.AbstractConnector`

I don't think this is nicely expressable with the current filters.

* `pattern` operates on the message, not logger
* `loggers` is an allowlist, not a blocklist

So I was thinking of introducing a `logger-pattern` or `loggers-blocklist`. Maybe both.

Thoughts? @r0man

**Comment by r0man** [comment]
Sounds good to me. Maybe choose a more obvious name? rename `loggers` to `included-loggers`, and use `excluded-loggers`?

**Comment by vemv** [comment]
I guess we can perform that breaking change and smooth it out Elisp-side.

However I'd prefer loggers-allowlist (or loggers-whitelist) to clearly reflect that that _only_ allowlisted would make it in.

(as I see it, `included-loggers` doesn't capture so well the "exclusive inclusion" concept).

Self-assigned

**Comment by r0man** [comment]
Ok, let's go with allow/block (or anything similar) rather than black/white.
