### ISSUE TITLE
Feature: timbre support

### ISSUE THREAD

**Issue by yenda** [clojure-emacs/logjam#8]
Would be great to have timbre supported as a framework. The lib doesn’t use any Java framework

**Comment by vemv** [comment]
@r0man 👋, is Timbre support something that we had considered?

**Comment by r0man** [comment]
I only looked at the Java logging frameworks so far, JUL, Logback, and Log4j.
Looking at https://github.com/taoensso/timbre/wiki/2-Appenders I think it is doable.
I think we would need to merge our own appender into Timbre's config when we attach to it, and remove it when we detach.

**Comment by vemv** [comment]
Sounds reasonable!

**Comment by vemv** [comment]
I'll work on this one

**Comment by vemv** [comment]
This will be released CIDER-side later in the week 🎉

**Comment by vemv** [comment]
https://github.com/clojure-emacs/cider/releases/tag/v1.13.0
